modLoader="javafml"
loaderVersion="[4,)"
license="GNU GPL 3.0"

[[mods]]
modId="anm"
version="${version}"
displayName="nomoreadvancement"
authors="thePlaceholder"
description='''
Advancement... No More !!!™ is a Minecraft mod allowing Modpack Makers to remove ALL advancement.
'''
logoFile="assets/anm/icon.png"

[[dependencies.anm]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.anm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"