org.gradle.jvmargs=-Xmx1G

minecraft_version=1.21.1
yarn_mappings = 1.21.1+build.1
yarn_mappings_patch_neoforge_version = 1.21+build.4

archives_name=anm
mod_version=2.1.0
maven_group=org.theplaceholder
enabled_platforms=fabric,neoforge

fabric_loader_version=0.16.13
neoforge_version=21.1.145

curseforge_id=959354
modrinth_id=mQCROijy

changelog="Updated to 1.21.1"
