org.gradle.jvmargs=-Xmx1G

minecraft_version=1.18.2
yarn_mappings = 1.18.2+build.4

archives_name=anm
mod_version=2.0.1
maven_group=org.theplaceholder
enabled_platforms=fabric,forge

fabric_loader_version=0.16.13
forge_version=1.18.2-40.3.10

curseforge_id=959354
modrinth_id=mQCROijy

changelog="Downgraded to 1.18.2 for https://legacy.curseforge.com/members/focused_jones42"
