modLoader="javafml"
loaderVersion="[4,)"
license="GNU GPL 3.0"

[[mods]]
modId="nomoreadvancement"
version="${version}"
displayName="nomoreadvancement"
authors="thePlaceholder"
description='''

'''

[[dependencies.nomoreadvancement]]
   modId="neoforge"
   type="required"
   versionRange="[21.0.0-beta,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.nomoreadvancement]]
   modId="minecraft"
   type="required"
   versionRange="[1.21,)"
   ordering="NONE"
   side="BOTH"

[[mixins]]
   config="nomoreadvancement.mixins.json"
