modLoader="javafml"
loaderVersion="[4,)"
license="GNU GPL 3.0"

[[mods]]
modId="anm"
version="${version}"
displayName="nomoreadvancement"
authors="thePlaceholder"
description='''
Advancement... No More !!!™ is a Minecraft mod allowing Modpack Makers to remove ALL advancement.
'''
logoFile = "icon.png"

[[dependencies.anm]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.anm]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "anm.mixins.json"
